1\.\ exception\ \'Exception\'\ with\ message\ \'aaa\'\ in\ [^
]+bug52361\.php\:5\
Stack\ trace\:\
\#0\ [^
]+bug52361\.php\(16\)\:\ aaa\-\>\_\_destruct\(\)\
\#1\ [^
]+bug52361\.php\(16\)\:\ bbb\(\)\
\#2\ \{main\}\
2\.\ exception\ \'Exception\'\ with\ message\ \'bbb\'\ in\ [^
]+bug52361\.php\:13\
Stack\ trace\:\
\#0\ [^
]+bug52361\.php\(16\)\:\ bbb\(\)\
\#1\ \{main\}